# Generated by Django 4.1 on 2022-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
